version: '3.8'
services:
  # postgreSQL DB container
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vue_sample_db

    volumes:
      # container scoped bind mound for sql database seed
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  # Adminer container
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db 
      ADMINER_DEFAULT_DB_NAME: vue_sample_db

  # Redis cache container
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  # middleware server
  server:
    build: server
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      # container scoped bind mount on server directory to enable hot reload. node_modules is in .dockerignore to prevent dependency
      # sharing between container and host machine, as OSes may be different. To preserve node_modules at the container level, the
      # volume nodemodules is created
      - ./server:/server/
      - vue_sample_nodemodules_server:/server/node_modules
    depends_on:
      - db
      - redis
  
  # frontend running vite
  frontend:
    build: frontend
    command: npm run dev 
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend/
      - vue_sample_nodemodules_frontend:/frontend/node_modules  
    depends_on:
      - server

volumes:
  vue_sample_nodemodules_server: 
  vue_sample_nodemodules_frontend:

